# Generated by Django 3.2.5 on 2022-10-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
                ('bin', models.CharField(max_length=30)),
                ('parent', models.CharField(max_length=30)),
                ('holdingunit', models.CharField(max_length=30)),
                ('productcode', models.CharField(max_length=30)),
                ('qty', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_workflow', models.CharField(max_length=30)),
                ('workflowtype', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=30)),
                ('productcode', models.CharField(max_length=30)),
                ('sourcearea', models.CharField(max_length=30)),
                ('sourcebin', models.CharField(max_length=30)),
                ('sourceqty_i', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('sourceqty_r', models.IntegerField(default=0)),
                ('targetqty', models.IntegerField(default=0)),
                ('targetbin', models.CharField(max_length=30)),
                ('targetarea', models.CharField(max_length=30)),
                ('holdingunit', models.CharField(max_length=30)),
                ('transactiondate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='invoice',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
