# Generated by Django 3.2.5 on 2022-10-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0002_auto_20221023_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='sourceqty_i',
            new_name='Initial_SOH',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='sourceqty_r',
            new_name='Result_SOH',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='targetqty',
        ),
        migrations.AddField(
            model_name='transactions',
            name='user_transactions',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transactiondate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
