# Generated by Django 3.2.5 on 2022-10-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0003_auto_20221023_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='assigned_user',
            new_name='assigned_user1',
        ),
        migrations.AddField(
            model_name='delivery',
            name='assigned_user2',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='assigned_user3',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
