# Generated by Django 3.2.5 on 2022-11-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0004_auto_20221023_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bincontent',
            name='allocated',
            field=models.CharField(default='False', max_length=30),
        ),
        migrations.AlterField(
            model_name='bincontent',
            name='full',
            field=models.CharField(default='False', max_length=30),
        ),
        migrations.AlterField(
            model_name='bincontent',
            name='route',
            field=models.CharField(default='False', max_length=30),
        ),
    ]
