# Generated by Django 3.2.5 on 2022-11-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0007_afterpickstaging_customers_employee_orderlines_ordermanagement_orders_routecodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routecodes',
            name='area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='routecodes',
            name='areatype',
            field=models.CharField(max_length=50),
        ),
    ]
