# Generated by Django 3.2.5 on 2022-11-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0008_auto_20221123_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='routing',
            name='route_user',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
