# Generated by Django 3.2.5 on 2022-11-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0009_routing_route_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='createdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='requesteddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='shippeddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
