# Generated by Django 3.2.5 on 2022-11-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0011_auto_20221129_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermanagement',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
