# Generated by Django 3.2.5 on 2022-12-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0012_ordermanagement_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermanagement',
            name='pickqty1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermanagement',
            name='pickqty2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermanagement',
            name='pickqty3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermanagement',
            name='status1',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermanagement',
            name='status2',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermanagement',
            name='status3',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
