# Generated by Django 3.2.5 on 2022-12-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0013_auto_20221205_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermanagement',
            name='unallocatedqty',
            field=models.IntegerField(default=0),
        ),
    ]
