# Generated by Django 3.2.5 on 2022-12-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0014_ordermanagement_unallocatedqty'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.CharField(max_length=30)),
                ('productcode', models.CharField(max_length=30)),
                ('orderedqty', models.IntegerField(default=0)),
                ('available_qty', models.IntegerField(default=0)),
                ('allocated_bin', models.CharField(max_length=30)),
                ('allocated_bin_qty', models.IntegerField(default=0)),
                ('allocated_user', models.CharField(max_length=30)),
                ('allocated_qty', models.IntegerField(default=0)),
                ('picked_qty', models.IntegerField(default=0)),
                ('Unallocated_qty', models.IntegerField(default=0)),
                ('pick_hu', models.CharField(max_length=30)),
                ('pack_hu', models.CharField(max_length=30)),
                ('ship_hu', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
