# Generated by Django 3.2.5 on 2022-12-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0015_orderschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlines',
            name='qtypacked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderlines',
            name='qtypicked',
            field=models.IntegerField(default=0),
        ),
    ]
