# Generated by Django 3.2.5 on 2023-01-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0016_auto_20221230_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocateCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=30)),
                ('active', models.CharField(max_length=30)),
                ('orderno', models.CharField(max_length=30)),
            ],
        ),
    ]
