# Generated by Django 3.2.5 on 2023-01-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0018_allocatecapacity_station_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bincontent',
            name='avail_qty',
            field=models.IntegerField(default=0),
        ),
    ]
