# Generated by Django 3.2.5 on 2023-01-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0020_afterpickstaging_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterpickstaging',
            name='position',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afterpickstaging',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
