# Generated by Django 3.2.5 on 2023-01-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0022_auto_20230114_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterpickstaging',
            name='hutype',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
