# Generated by Django 3.2.5 on 2023-01-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0023_afterpickstaging_hutype'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderschedule',
            name='hutype',
            field=models.CharField(default='HU', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderschedule',
            name='packed_qty',
            field=models.IntegerField(default=0),
        ),
    ]
