# Generated by Django 3.2.5 on 2023-02-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0025_afterpickstaging_orderno'),
    ]

    operations = [
        migrations.CreateModel(
            name='DUConfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('du', models.CharField(max_length=30)),
                ('orderno', models.CharField(max_length=30)),
                ('productcode', models.CharField(max_length=30)),
                ('qty', models.IntegerField(default=0)),
                ('packdate', models.DateTimeField(blank=True, null=True)),
                ('box_type', models.CharField(max_length=30)),
            ],
        ),
    ]
