# Generated by Django 3.2.5 on 2023-02-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0026_duconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='duconfirm',
            name='packer',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duconfirm',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
