# Generated by Django 3.2.5 on 2023-02-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0028_shipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afterpickstaging',
            old_name='position',
            new_name='packer_user',
        ),
    ]
