# Generated by Django 3.2.5 on 2023-02-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0029_rename_position_afterpickstaging_packer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='duconfirm',
            name='status',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
