# Generated by Django 3.2.5 on 2023-03-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0030_duconfirm_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='avail_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='onhold_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='soh',
            field=models.IntegerField(default=0),
        ),
    ]
